# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-29 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist_app', '0002_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='wished_by',
            field=models.ManyToManyField(related_name='wish', to='wishlist_app.User'),
        ),
        migrations.RemoveField(
            model_name='list',
            name='added_by',
        ),
        migrations.AddField(
            model_name='list',
            name='added_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='add', to='wishlist_app.User'),
            preserve_default=False,
        ),
    ]
